// Generated by Apple Swift version 5.0.1 effective-4.2 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Persistence",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("BtcTransaction")
@interface BtcTransaction : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSObject;

@interface BtcTransaction (SWIFT_EXTENSION(Persistence))
@property (nonatomic) int32_t blockchainId;
@property (nonatomic, copy) NSString * _Nullable blockHash;
@property (nonatomic) int64_t blockNumber;
@property (nonatomic, copy) NSDate * _Nullable blockTimestamp;
@property (nonatomic, copy) NSString * _Nullable coinBase;
@property (nonatomic) int64_t correncyConversion;
@property (nonatomic, copy) NSString * _Nullable from;
@property (nonatomic, strong) NSObject * _Nullable fromAddresses;
@property (nonatomic) int64_t gas;
@property (nonatomic) int64_t gasPrice;
@property (nonatomic, copy) NSString * _Nullable hashPK;
@property (nonatomic) int64_t lockTime;
@property (nonatomic, strong) NSObject * _Nullable scriptPubKey;
@property (nonatomic, copy) NSString * _Nullable to;
@property (nonatomic, strong) NSObject * _Nullable toAddresses;
@property (nonatomic, copy) NSString * _Nullable txId;
@property (nonatomic) int64_t value;
@property (nonatomic) int64_t voutIndex;
@property (nonatomic) BOOL vOutSpent;
@end


SWIFT_CLASS_NAMED("Connection")
@interface Connection : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Connection (SWIFT_EXTENSION(Persistence))
@property (nonatomic, strong) NSObject * _Nullable sharedAccounts;
@property (nonatomic, strong) NSObject * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable userIdString;
@property (nonatomic, strong) NSObject * _Nullable viewableAccounts;
@end


SWIFT_CLASS_NAMED("ConnectionRequest")
@interface ConnectionRequest : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ConnectionRequest (SWIFT_EXTENSION(Persistence))
@property (nonatomic, copy) NSString * _Nullable connectionRequestId;
@property (nonatomic) BOOL connectionRequestInitiator;
@property (nonatomic) int16_t status;
@property (nonatomic, copy) NSString * _Nullable userId;
@end


SWIFT_CLASS_NAMED("ConnectionSharedAccount")
@interface ConnectionSharedAccount : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ConnectionSharedAccount (SWIFT_EXTENSION(Persistence))
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic) BOOL autoShare;
@property (nonatomic) int32_t blockchainId;
@property (nonatomic) BOOL isMyAccount;
@property (nonatomic, copy) NSString * _Nullable nickname;
@property (nonatomic, copy) NSString * _Nullable userId;
@end


SWIFT_CLASS_NAMED("Contacts")
@interface Contacts : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Contacts (SWIFT_EXTENSION(Persistence))
@property (nonatomic, copy) NSString * _Nullable info;
@property (nonatomic, copy) NSString * _Nullable type;
@end


SWIFT_CLASS_NAMED("LatestMarketValue")
@interface LatestMarketValue : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface LatestMarketValue (SWIFT_EXTENSION(Persistence))
@property (nonatomic) int32_t blockchainId;
@property (nonatomic, copy) NSString * _Nullable closePrice;
@property (nonatomic, copy) NSString * _Nullable openPrice;
@property (nonatomic, copy) NSString * _Nullable symbol;
@property (nonatomic, copy) NSDate * _Nullable timestamp;
@end


SWIFT_CLASS_NAMED("PendingRequest")
@interface PendingRequest : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface PendingRequest (SWIFT_EXTENSION(Persistence))
@property (nonatomic, copy) NSString * _Nullable connectionRequestId;
@property (nonatomic, strong) NSObject * _Nullable receiver;
@property (nonatomic, copy) NSString * _Nullable receiverId;
@property (nonatomic, strong) NSObject * _Nullable sender;
@property (nonatomic, copy) NSString * _Nullable senderId;
@end


SWIFT_CLASS_NAMED("SmartContract")
@interface SmartContract : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface SmartContract (SWIFT_EXTENSION(Persistence))
@property (nonatomic) int32_t blockchainId;
@property (nonatomic, copy) NSString * _Nullable contractAddress;
@property (nonatomic) int32_t decimal;
@property (nonatomic, copy) NSString * _Nullable icon;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable shortName;
@property (nonatomic, copy) NSString * _Nullable type;
@end


SWIFT_CLASS_NAMED("Transaction")
@interface Transaction : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Transaction (SWIFT_EXTENSION(Persistence))
@property (nonatomic) int32_t blockchainId;
@property (nonatomic, copy) NSString * _Nullable blockHash;
@property (nonatomic) int64_t blockNumber;
@property (nonatomic, copy) NSDate * _Nullable blockTimestamp;
@property (nonatomic) double cashValue;
@property (nonatomic, copy) NSString * _Nullable from;
@property (nonatomic) BOOL fromUser;
@property (nonatomic) int64_t gas;
@property (nonatomic) int64_t gasPrice;
@property (nonatomic, copy) NSString * _Nullable gasUsed;
@property (nonatomic, copy) NSString * _Nullable hashPK;
@property (nonatomic, copy) NSString * _Nullable input;
@property (nonatomic, copy) NSString * _Nullable isSmartContract;
@property (nonatomic, copy) NSString * _Nullable smartContractAddress;
@property (nonatomic, copy) NSString * _Nullable to;
@property (nonatomic) int64_t tokenValue;
@property (nonatomic) BOOL toUser;
@property (nonatomic) double value;
@end


SWIFT_CLASS_NAMED("User")
@interface User : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface User (SWIFT_EXTENSION(Persistence))
@property (nonatomic, copy) NSString * _Nullable avatar;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable userId;
@end

@class NSCoder;

SWIFT_CLASS("_TtC11Persistence9VMAccount")
@interface VMAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence20VMBitcoinTransaction")
@interface VMBitcoinTransaction : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence20VMBitcoinTransaction")
@interface VMBitcoinTransaction : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence9VMContact")
@interface VMContact : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence12VMERC20Token")
@interface VMERC20Token : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence21VMEthereumTransaction")
@interface VMEthereumTransaction : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence13VMMarketValue")
@interface VMMarketValue : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence17VMPendingRequests")
@interface VMPendingRequests : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence17VMRequestUserData")
@interface VMRequestUserData : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence15VMSharedAccount")
@interface VMSharedAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence16VMUserConnection")
@interface VMUserConnection : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11Persistence10VMUserData")
@interface VMUserData : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("WalletAccount")
@interface WalletAccount : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface WalletAccount (SWIFT_EXTENSION(Persistence))
@property (nonatomic, copy) NSString * _Nullable accountId;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic) BOOL autoShare;
@property (nonatomic) int32_t blockchainId;
@property (nonatomic, copy) NSString * _Nullable nickname;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
