// Generated by Apple Swift version 5.0.1 effective-4.2 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import MQTTClient;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MQTTHandler",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC11MQTTHandler17MQTTSessionHelper")
@interface MQTTSessionHelper : NSObject <MQTTSessionDelegate, MQTTSessionManagerDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)connect;
- (BOOL)handleMessageWithFeedBack:(NSData * _Null_unspecified)data onTopic:(NSString * _Null_unspecified)topic retained:(BOOL)retained SWIFT_WARN_UNUSED_RESULT;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end

@class NSCoder;

SWIFT_CLASS("_TtC11MQTTHandler15VWAccountShared")
@interface VWAccountShared : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler23VWAccountSharedResponse")
@interface VWAccountSharedResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler17VWAccountUnshared")
@interface VWAccountUnshared : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler12VWAddAccount")
@interface VWAddAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler20VWAddAccountResponse")
@interface VWAddAccountResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler12VWAddContact")
@interface VWAddContact : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler20VWAddContactResponse")
@interface VWAddContactResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler26VWApproveConnectionRequest")
@interface VWApproveConnectionRequest : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler34VWApproveConnectionRequestResponse")
@interface VWApproveConnectionRequestResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler23VWChangeAccountNickname")
@interface VWChangeAccountNickname : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler31VWChangeAccountNicknameResponse")
@interface VWChangeAccountNicknameResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler12VWConnection")
@interface VWConnection : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler19VWConnectionRemoved")
@interface VWConnectionRemoved : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler19VWConnectionRequest")
@interface VWConnectionRequest : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler21VWConnectionRequested")
@interface VWConnectionRequested : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler25VWConnectionSharedAccount")
@interface VWConnectionSharedAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler9VWContact")
@interface VWContact : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler23VWDenyConnectionRequest")
@interface VWDenyConnectionRequest : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler31VWDenyConnectionRequestResponse")
@interface VWDenyConnectionRequestResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler6VWEcho")
@interface VWEcho : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler14VWEchoResponse")
@interface VWEchoResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler14VWEmptyMessage")
@interface VWEmptyMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler15VWErrorCallback")
@interface VWErrorCallback : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler21VWEthereumTransaction")
@interface VWEthereumTransaction : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler16VWGetContactInfo")
@interface VWGetContactInfo : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler24VWGetContactInfoResponse")
@interface VWGetContactInfoResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler19VWGetMyUserResponse")
@interface VWGetMyUserResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler9VWGetUser")
@interface VWGetUser : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler27VWGetUserConnectionResponse")
@interface VWGetUserConnectionResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler19VWLatestMarketValue")
@interface VWLatestMarketValue : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler13VWMarketValue")
@interface VWMarketValue : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler26VWPendingConnectionRequest")
@interface VWPendingConnectionRequest : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler16VWPendingRequest")
@interface VWPendingRequest : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler25VWQueuedAddAccountMessage")
@interface VWQueuedAddAccountMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler32VWQueuedApproveConnectionMessage")
@interface VWQueuedApproveConnectionMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler36VWQueuedChangeAccountNicknameMessage")
@interface VWQueuedChangeAccountNicknameMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler29VWQueuedDenyConnectionMessage")
@interface VWQueuedDenyConnectionMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler28VWQueuedRemoveAccountMessage")
@interface VWQueuedRemoveAccountMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler31VWQueuedRemoveConnectionMessage")
@interface VWQueuedRemoveConnectionMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler32VWQueuedRequestConnectionMessage")
@interface VWQueuedRequestConnectionMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler24VWQueuedSetAvatarMessage")
@interface VWQueuedSetAvatarMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler22VWQueuedSetNameMessage")
@interface VWQueuedSetNameMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler27VWQueuedShareAccountMessage")
@interface VWQueuedShareAccountMessage : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler15VWRemoveAccount")
@interface VWRemoveAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler23VWRemoveAccountResponse")
@interface VWRemoveAccountResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler18VWRemoveConnection")
@interface VWRemoveConnection : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler26VWRemoveConnectionResponse")
@interface VWRemoveConnectionResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler19VWRequestConnection")
@interface VWRequestConnection : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler27VWRequestConnectionApproved")
@interface VWRequestConnectionApproved : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler25VWRequestConnectionDenied")
@interface VWRequestConnectionDenied : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler26VWRequestConnectionPending")
@interface VWRequestConnectionPending : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler11VWSetAvatar")
@interface VWSetAvatar : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler19VWSetAvatarResponse")
@interface VWSetAvatarResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler9VWSetName")
@interface VWSetName : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler17VWSetNameResponse")
@interface VWSetNameResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler14VWShareAccount")
@interface VWShareAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler19VWSimpleTransaction")
@interface VWSimpleTransaction : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler16VWUnshareAccount")
@interface VWUnshareAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler24VWUnshareAccountResponse")
@interface VWUnshareAccountResponse : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler6VWUser")
@interface VWUser : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler19VWUserSharedAccount")
@interface VWUserSharedAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler21VWUserTransactionData")
@interface VWUserTransactionData : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC11MQTTHandler15VWWalletAccount")
@interface VWWalletAccount : NSObject <NSCoding>
/// <ul>
///   <li>
///     NSCoding required method.
///   </li>
///   <li>
///     Encodes mode properties into the decoder
///   </li>
/// </ul>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
/// <ul>
///   <li>
///     NSCoding required initializer.
///   </li>
///   <li>
///     Fills the data from the passed decoder
///   </li>
/// </ul>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
